//
//  File.swift
//  Currency-Converter
//
//  Created by Minh Trương on 14/12/24.
//

import Foundation

struct Country {
    var countryName: String
    var countryCode: String
    var countryCurrency: String
    var countryFlag: String
}

extension Country{
    static var countryData: [Country] {
        return [
            Country(countryName: "South Georgia", countryCode: "GS", countryCurrency: "SHP", countryFlag: "🇬🇸"),
            Country(countryName: "Grenada", countryCode: "GD", countryCurrency: "XCD", countryFlag: "🇬🇩"),
            Country(countryName: "Switzerland", countryCode: "CH", countryCurrency: "CHF", countryFlag: "🇨🇭"),
            Country(countryName: "Sierra Leone", countryCode: "SL", countryCurrency: "SLL", countryFlag: "🇸🇱"),
            Country(countryName: "Hungary", countryCode: "HU", countryCurrency: "HUF", countryFlag: "🇭🇺"),
            Country(countryName: "Taiwan", countryCode: "TW", countryCurrency: "TWD", countryFlag: "🇹🇼"),
            Country(countryName: "Wallis and Futuna", countryCode: "WF", countryCurrency: "XPF", countryFlag: "🇼🇫"),
            Country(countryName: "Barbados", countryCode: "BB", countryCurrency: "BBD", countryFlag: "🇧🇧"),
            Country(countryName: "Pitcairn Islands", countryCode: "PN", countryCurrency: "NZD", countryFlag: "🇵🇳"),
            Country(countryName: "Ivory Coast", countryCode: "CI", countryCurrency: "XOF", countryFlag: "🇨🇮"),
            Country(countryName: "Tunisia", countryCode: "TN", countryCurrency: "TND", countryFlag: "🇹🇳"),
            Country(countryName: "Italy", countryCode: "IT", countryCurrency: "EUR", countryFlag: "🇮🇹"),
            Country(countryName: "Benin", countryCode: "BJ", countryCurrency: "XOF", countryFlag: "🇧🇯"),
            Country(countryName: "Indonesia", countryCode: "ID", countryCurrency: "IDR", countryFlag: "🇮🇩"),
            Country(countryName: "Cape Verde", countryCode: "CV", countryCurrency: "CVE", countryFlag: "🇨🇻"),
            Country(countryName: "Saint Kitts and Nevis", countryCode: "KN", countryCurrency: "XCD", countryFlag: "🇰🇳"),
            Country(countryName: "Laos", countryCode: "LA", countryCurrency: "LAK", countryFlag: "🇱🇦"),
            Country(countryName: "Caribbean Netherlands", countryCode: "BQ", countryCurrency: "USD", countryFlag: "🇧🇶"),
            Country(countryName: "Uganda", countryCode: "UG", countryCurrency: "UGX", countryFlag: "🇺🇬"),
            Country(countryName: "Andorra", countryCode: "AD", countryCurrency: "EUR", countryFlag: "🇦🇩"),
            Country(countryName: "Burundi", countryCode: "BI", countryCurrency: "BIF", countryFlag: "🇧🇮"),
            Country(countryName: "South Africa", countryCode: "ZA", countryCurrency: "ZAR", countryFlag: "🇿🇦"),
            Country(countryName: "France", countryCode: "FR", countryCurrency: "EUR", countryFlag: "🇫🇷"),
            Country(countryName: "Libya", countryCode: "LY", countryCurrency: "LYD", countryFlag: "🇱🇾"),
            Country(countryName: "Mexico", countryCode: "MX", countryCurrency: "MXN", countryFlag: "🇲🇽"),
            Country(countryName: "Gabon", countryCode: "GA", countryCurrency: "XAF", countryFlag: "🇬🇦"),
            Country(countryName: "Northern Mariana Islands", countryCode: "MP", countryCurrency: "USD", countryFlag: "🇲🇵"),
            Country(countryName: "North Macedonia", countryCode: "MK", countryCurrency: "MKD", countryFlag: "🇲🇰"),
            Country(countryName: "China", countryCode: "CN", countryCurrency: "CNY", countryFlag: "🇨🇳"),
            Country(countryName: "Yemen", countryCode: "YE", countryCurrency: "YER", countryFlag: "🇾🇪"),
            Country(countryName: "Saint Barthélemy", countryCode: "BL", countryCurrency: "EUR", countryFlag: "🇧🇱"),
            Country(countryName: "Guernsey", countryCode: "GG", countryCurrency: "GBP", countryFlag: "🇬🇬"),
            Country(countryName: "Solomon Islands", countryCode: "SB", countryCurrency: "SBD", countryFlag: "🇸🇧"),
            Country(countryName: "Svalbard and Jan Mayen", countryCode: "SJ", countryCurrency: "NOK", countryFlag: "🇸🇯"),
            Country(countryName: "Faroe Islands", countryCode: "FO", countryCurrency: "DKK", countryFlag: "🇫🇴"),
            Country(countryName: "Uzbekistan", countryCode: "UZ", countryCurrency: "UZS", countryFlag: "🇺🇿"),
            Country(countryName: "Egypt", countryCode: "EG", countryCurrency: "EGP", countryFlag: "🇪🇬"),
            Country(countryName: "Senegal", countryCode: "SN", countryCurrency: "XOF", countryFlag: "🇸🇳"),
            Country(countryName: "Sri Lanka", countryCode: "LK", countryCurrency: "LKR", countryFlag: "🇱🇰"),
            Country(countryName: "Palestine", countryCode: "PS", countryCurrency: "EGP", countryFlag: "🇵🇸"),
            Country(countryName: "Bangladesh", countryCode: "BD", countryCurrency: "BDT", countryFlag: "🇧🇩"),
            Country(countryName: "Peru", countryCode: "PE", countryCurrency: "PEN", countryFlag: "🇵🇪"),
            Country(countryName: "Singapore", countryCode: "SG", countryCurrency: "SGD", countryFlag: "🇸🇬"),
            Country(countryName: "Turkey", countryCode: "TR", countryCurrency: "TRY", countryFlag: "🇹🇷"),
            Country(countryName: "Afghanistan", countryCode: "AF", countryCurrency: "AFN", countryFlag: "🇦🇫"),
            Country(countryName: "Aruba", countryCode: "AW", countryCurrency: "AWG", countryFlag: "🇦🇼"),
            Country(countryName: "Cook Islands", countryCode: "CK", countryCurrency: "CKD", countryFlag: "🇨🇰"),
            Country(countryName: "United Kingdom", countryCode: "GB", countryCurrency: "GBP", countryFlag: "🇬🇧"),
            Country(countryName: "Zambia", countryCode: "ZM", countryCurrency: "ZMW", countryFlag: "🇿🇲"),
            Country(countryName: "Finland", countryCode: "FI", countryCurrency: "EUR", countryFlag: "🇫🇮"),
            Country(countryName: "Niger", countryCode: "NE", countryCurrency: "XOF", countryFlag: "🇳🇪"),
            Country(countryName: "Christmas Island", countryCode: "CX", countryCurrency: "AUD", countryFlag: "🇨🇽"),
            Country(countryName: "Tokelau", countryCode: "TK", countryCurrency: "NZD", countryFlag: "🇹🇰"),
            Country(countryName: "Guinea-Bissau", countryCode: "GW", countryCurrency: "XOF", countryFlag: "🇬🇼"),
            Country(countryName: "Azerbaijan", countryCode: "AZ", countryCurrency: "AZN", countryFlag: "🇦🇿"),
            Country(countryName: "Réunion", countryCode: "RE", countryCurrency: "EUR", countryFlag: "🇷🇪"),
            Country(countryName: "Djibouti", countryCode: "DJ", countryCurrency: "DJF", countryFlag: "🇩🇯"),
            Country(countryName: "North Korea", countryCode: "KP", countryCurrency: "KPW", countryFlag: "🇰🇵"),
            Country(countryName: "Mauritius", countryCode: "MU", countryCurrency: "MUR", countryFlag: "🇲🇺"),
            Country(countryName: "Montserrat", countryCode: "MS", countryCurrency: "XCD", countryFlag: "🇲🇸"),
            Country(countryName: "United States Virgin Islands", countryCode: "VI", countryCurrency: "USD", countryFlag: "🇻🇮"),
            Country(countryName: "Colombia", countryCode: "CO", countryCurrency: "COP", countryFlag: "🇨🇴"),
            Country(countryName: "Greece", countryCode: "GR", countryCurrency: "EUR", countryFlag: "🇬🇷"),
            Country(countryName: "Croatia", countryCode: "HR", countryCurrency: "EUR", countryFlag: "🇭🇷"),
            Country(countryName: "Morocco", countryCode: "MA", countryCurrency: "MAD", countryFlag: "🇲🇦"),
            Country(countryName: "Algeria", countryCode: "DZ", countryCurrency: "DZD", countryFlag: "🇩🇿"),
            Country(countryName: "Antarctica", countryCode: "AQ", countryCurrency: "N/A", countryFlag: "🇦🇶"),
            Country(countryName: "Netherlands", countryCode: "NL", countryCurrency: "EUR", countryFlag: "🇳🇱"),
            Country(countryName: "Sudan", countryCode: "SD", countryCurrency: "SDG", countryFlag: "🇸🇩"),
            Country(countryName: "Fiji", countryCode: "FJ", countryCurrency: "FJD", countryFlag: "🇫🇯"),
            Country(countryName: "Liechtenstein", countryCode: "LI", countryCurrency: "CHF", countryFlag: "🇱🇮"),
            Country(countryName: "Nepal", countryCode: "NP", countryCurrency: "NPR", countryFlag: "🇳🇵"),
            Country(countryName: "Puerto Rico", countryCode: "PR", countryCurrency: "USD", countryFlag: "🇵🇷"),
            Country(countryName: "Georgia", countryCode: "GE", countryCurrency: "GEL", countryFlag: "🇬🇪"),
            Country(countryName: "Pakistan", countryCode: "PK", countryCurrency: "PKR", countryFlag: "🇵🇰"),
            Country(countryName: "Monaco", countryCode: "MC", countryCurrency: "EUR", countryFlag: "🇲🇨"),
            Country(countryName: "Botswana", countryCode: "BW", countryCurrency: "BWP", countryFlag: "🇧🇼"),
            Country(countryName: "Lebanon", countryCode: "LB", countryCurrency: "LBP", countryFlag: "🇱🇧"),
            Country(countryName: "Papua New Guinea", countryCode: "PG", countryCurrency: "PGK", countryFlag: "🇵🇬"),
            Country(countryName: "Mayotte", countryCode: "YT", countryCurrency: "EUR", countryFlag: "🇾🇹"),
            Country(countryName: "Dominican Republic", countryCode: "DO", countryCurrency: "DOP", countryFlag: "🇩🇴"),
            Country(countryName: "Norfolk Island", countryCode: "NF", countryCurrency: "AUD", countryFlag: "🇳🇫"),
            Country(countryName: "Bouvet Island", countryCode: "BV", countryCurrency: "N/A", countryFlag: "🇧🇻"),
            Country(countryName: "Qatar", countryCode: "QA", countryCurrency: "QAR", countryFlag: "🇶🇦"),
            Country(countryName: "Madagascar", countryCode: "MG", countryCurrency: "MGA", countryFlag: "🇲🇬"),
            Country(countryName: "India", countryCode: "IN", countryCurrency: "INR", countryFlag: "🇮🇳"),
            Country(countryName: "Syria", countryCode: "SY", countryCurrency: "SYP", countryFlag: "🇸🇾"),
            Country(countryName: "Montenegro", countryCode: "ME", countryCurrency: "EUR", countryFlag: "🇲🇪"),
            Country(countryName: "Eswatini", countryCode: "SZ", countryCurrency: "SZL", countryFlag: "🇸🇿"),
            Country(countryName: "Paraguay", countryCode: "PY", countryCurrency: "PYG", countryFlag: "🇵🇾"),
            Country(countryName: "El Salvador", countryCode: "SV", countryCurrency: "USD", countryFlag: "🇸🇻"),
            Country(countryName: "Ukraine", countryCode: "UA", countryCurrency: "UAH", countryFlag: "🇺🇦"),
            Country(countryName: "Isle of Man", countryCode: "IM", countryCurrency: "GBP", countryFlag: "🇮🇲"),
            Country(countryName: "Namibia", countryCode: "NA", countryCurrency: "NAD", countryFlag: "🇳🇦"),
            Country(countryName: "United Arab Emirates", countryCode: "AE", countryCurrency: "AED", countryFlag: "🇦🇪"),
            Country(countryName: "Bulgaria", countryCode: "BG", countryCurrency: "BGN", countryFlag: "🇧🇬"),
            Country(countryName: "Greenland", countryCode: "GL", countryCurrency: "DKK", countryFlag: "🇬🇱"),
            Country(countryName: "Germany", countryCode: "DE", countryCurrency: "EUR", countryFlag: "🇩🇪"),
            Country(countryName: "Cambodia", countryCode: "KH", countryCurrency: "KHR", countryFlag: "🇰🇭"),
            Country(countryName: "Iraq", countryCode: "IQ", countryCurrency: "IQD", countryFlag: "🇮🇶"),
            Country(countryName: "French Southern and Antarctic Lands", countryCode: "TF", countryCurrency: "EUR", countryFlag: "🇹🇫"),
            Country(countryName: "Sweden", countryCode: "SE", countryCurrency: "SEK", countryFlag: "🇸🇪"),
            Country(countryName: "Cuba", countryCode: "CU", countryCurrency: "CUC", countryFlag: "🇨🇺"),
            Country(countryName: "Kyrgyzstan", countryCode: "KG", countryCurrency: "KGS", countryFlag: "🇰🇬"),
            Country(countryName: "Russia", countryCode: "RU", countryCurrency: "RUB", countryFlag: "🇷🇺"),
            Country(countryName: "Malaysia", countryCode: "MY", countryCurrency: "MYR", countryFlag: "🇲🇾"),
            Country(countryName: "São Tomé and Príncipe", countryCode: "ST", countryCurrency: "STN", countryFlag: "🇸🇹"),
            Country(countryName: "Cyprus", countryCode: "CY", countryCurrency: "EUR", countryFlag: "🇨🇾"),
            Country(countryName: "Canada", countryCode: "CA", countryCurrency: "CAD", countryFlag: "🇨🇦"),
            Country(countryName: "Malawi", countryCode: "MW", countryCurrency: "MWK", countryFlag: "🇲🇼"),
            Country(countryName: "Saudi Arabia", countryCode: "SA", countryCurrency: "SAR", countryFlag: "🇸🇦"),
            Country(countryName: "Bosnia and Herzegovina", countryCode: "BA", countryCurrency: "BAM", countryFlag: "🇧🇦"),
            Country(countryName: "Ethiopia", countryCode: "ET", countryCurrency: "ETB", countryFlag: "🇪🇹"),
            Country(countryName: "Spain", countryCode: "ES", countryCurrency: "EUR", countryFlag: "🇪🇸"),
            Country(countryName: "Slovenia", countryCode: "SI", countryCurrency: "EUR", countryFlag: "🇸🇮"),
            Country(countryName: "Oman", countryCode: "OM", countryCurrency: "OMR", countryFlag: "🇴🇲"),
            Country(countryName: "Saint Pierre and Miquelon", countryCode: "PM", countryCurrency: "EUR", countryFlag: "🇵🇲"),
            Country(countryName: "Macau", countryCode: "MO", countryCurrency: "MOP", countryFlag: "🇲🇴"),
            Country(countryName: "San Marino", countryCode: "SM", countryCurrency: "EUR", countryFlag: "🇸🇲"),
            Country(countryName: "Lesotho", countryCode: "LS", countryCurrency: "LSL", countryFlag: "🇱🇸"),
            Country(countryName: "Marshall Islands", countryCode: "MH", countryCurrency: "USD", countryFlag: "🇲🇭"),
            Country(countryName: "Sint Maarten", countryCode: "SX", countryCurrency: "ANG", countryFlag: "🇸🇽"),
            Country(countryName: "Iceland", countryCode: "IS", countryCurrency: "ISK", countryFlag: "🇮🇸"),
            Country(countryName: "Luxembourg", countryCode: "LU", countryCurrency: "EUR", countryFlag: "🇱🇺"),
            Country(countryName: "Argentina", countryCode: "AR", countryCurrency: "ARS", countryFlag: "🇦🇷"),
            Country(countryName: "Turks and Caicos Islands", countryCode: "TC", countryCurrency: "USD", countryFlag: "🇹🇨"),
            Country(countryName: "Nauru", countryCode: "NR", countryCurrency: "AUD", countryFlag: "🇳🇷"),
            Country(countryName: "Cocos (Keeling) Islands", countryCode: "CC", countryCurrency: "AUD", countryFlag: "🇨🇨"),
            Country(countryName: "Western Sahara", countryCode: "EH", countryCurrency: "DZD", countryFlag: "🇪🇭"),
            Country(countryName: "Dominica", countryCode: "DM", countryCurrency: "XCD", countryFlag: "🇩🇲"),
            Country(countryName: "Costa Rica", countryCode: "CR", countryCurrency: "CRC", countryFlag: "🇨🇷"),
            Country(countryName: "Australia", countryCode: "AU", countryCurrency: "AUD", countryFlag: "🇦🇺"),
            Country(countryName: "Thailand", countryCode: "TH", countryCurrency: "THB", countryFlag: "🇹🇭"),
            Country(countryName: "Haiti", countryCode: "HT", countryCurrency: "HTG", countryFlag: "🇭🇹"),
            Country(countryName: "Tuvalu", countryCode: "TV", countryCurrency: "AUD", countryFlag: "🇹🇻"),
            Country(countryName: "Honduras", countryCode: "HN", countryCurrency: "HNL", countryFlag: "🇭🇳"),
            Country(countryName: "Equatorial Guinea", countryCode: "GQ", countryCurrency: "XAF", countryFlag: "🇬🇶"),
            Country(countryName: "Saint Lucia", countryCode: "LC", countryCurrency: "XCD", countryFlag: "🇱🇨"),
            Country(countryName: "French Polynesia", countryCode: "PF", countryCurrency: "XPF", countryFlag: "🇵🇫"),
            Country(countryName: "Belarus", countryCode: "BY", countryCurrency: "BYN", countryFlag: "🇧🇾"),
            Country(countryName: "Latvia", countryCode: "LV", countryCurrency: "EUR", countryFlag: "🇱🇻"),
            Country(countryName: "Palau", countryCode: "PW", countryCurrency: "USD", countryFlag: "🇵🇼"),
            Country(countryName: "Guadeloupe", countryCode: "GP", countryCurrency: "EUR", countryFlag: "🇬🇵"),
            Country(countryName: "Philippines", countryCode: "PH", countryCurrency: "PHP", countryFlag: "🇵🇭"),
            Country(countryName: "Gibraltar", countryCode: "GI", countryCurrency: "GIP", countryFlag: "🇬🇮"),
            Country(countryName: "Denmark", countryCode: "DK", countryCurrency: "DKK", countryFlag: "🇩🇰"),
            Country(countryName: "Cameroon", countryCode: "CM", countryCurrency: "XAF", countryFlag: "🇨🇲"),
            Country(countryName: "Guinea", countryCode: "GN", countryCurrency: "GNF", countryFlag: "🇬🇳"),
            Country(countryName: "Bahrain", countryCode: "BH", countryCurrency: "BHD", countryFlag: "🇧🇭"),
            Country(countryName: "Suriname", countryCode: "SR", countryCurrency: "SRD", countryFlag: "🇸🇷"),
            Country(countryName: "DR Congo", countryCode: "CD", countryCurrency: "CDF", countryFlag: "🇨🇩"),
            Country(countryName: "Somalia", countryCode: "SO", countryCurrency: "SOS", countryFlag: "🇸🇴"),
            Country(countryName: "Czechia", countryCode: "CZ", countryCurrency: "CZK", countryFlag: "🇨🇿"),
            Country(countryName: "New Caledonia", countryCode: "NC", countryCurrency: "XPF", countryFlag: "🇳🇨"),
            Country(countryName: "Vanuatu", countryCode: "VU", countryCurrency: "VUV", countryFlag: "🇻🇺"),
            Country(countryName: "Saint Helena, Ascension and Tristan da Cunha", countryCode: "SH", countryCurrency: "GBP", countryFlag: "🇸🇭"),
            Country(countryName: "Togo", countryCode: "TG", countryCurrency: "XOF", countryFlag: "🇹🇬"),
            Country(countryName: "British Virgin Islands", countryCode: "VG", countryCurrency: "USD", countryFlag: "🇻🇬"),
            Country(countryName: "Kenya", countryCode: "KE", countryCurrency: "KES", countryFlag: "🇰🇪"),
            Country(countryName: "Niue", countryCode: "NU", countryCurrency: "NZD", countryFlag: "🇳🇺"),
            Country(countryName: "Heard Island and McDonald Islands", countryCode: "HM", countryCurrency: "N/A", countryFlag: "🇭🇲"),
            Country(countryName: "Rwanda", countryCode: "RW", countryCurrency: "RWF", countryFlag: "🇷🇼"),
            Country(countryName: "Estonia", countryCode: "EE", countryCurrency: "EUR", countryFlag: "🇪🇪"),
            Country(countryName: "Romania", countryCode: "RO", countryCurrency: "RON", countryFlag: "🇷🇴"),
            Country(countryName: "Trinidad and Tobago", countryCode: "TT", countryCurrency: "TTD", countryFlag: "🇹🇹"),
            Country(countryName: "Guyana", countryCode: "GY", countryCurrency: "GYD", countryFlag: "🇬🇾"),
            Country(countryName: "Timor-Leste", countryCode: "TL", countryCurrency: "USD", countryFlag: "🇹🇱"),
            Country(countryName: "Vietnam", countryCode: "VN", countryCurrency: "VND", countryFlag: "🇻🇳"),
            Country(countryName: "Uruguay", countryCode: "UY", countryCurrency: "UYU", countryFlag: "🇺🇾"),
            Country(countryName: "Vatican City", countryCode: "VA", countryCurrency: "EUR", countryFlag: "🇻🇦"),
            Country(countryName: "Hong Kong", countryCode: "HK", countryCurrency: "HKD", countryFlag: "🇭🇰"),
            Country(countryName: "Austria", countryCode: "AT", countryCurrency: "EUR", countryFlag: "🇦🇹"),
            Country(countryName: "Antigua and Barbuda", countryCode: "AG", countryCurrency: "XCD", countryFlag: "🇦🇬"),
            Country(countryName: "Turkmenistan", countryCode: "TM", countryCurrency: "TMT", countryFlag: "🇹🇲"),
            Country(countryName: "Mozambique", countryCode: "MZ", countryCurrency: "MZN", countryFlag: "🇲🇿"),
            Country(countryName: "Panama", countryCode: "PA", countryCurrency: "PAB", countryFlag: "🇵🇦"),
            Country(countryName: "Micronesia", countryCode: "FM", countryCurrency: "USD", countryFlag: "🇫🇲"),
            Country(countryName: "Ireland", countryCode: "IE", countryCurrency: "EUR", countryFlag: "🇮🇪"),
            Country(countryName: "Curaçao", countryCode: "CW", countryCurrency: "ANG", countryFlag: "🇨🇼"),
            Country(countryName: "French Guiana", countryCode: "GF", countryCurrency: "EUR", countryFlag: "🇬🇫"),
            Country(countryName: "Norway", countryCode: "NO", countryCurrency: "NOK", countryFlag: "🇳🇴"),
            Country(countryName: "Åland Islands", countryCode: "AX", countryCurrency: "EUR", countryFlag: "🇦🇽"),
            Country(countryName: "Central African Republic", countryCode: "CF", countryCurrency: "XAF", countryFlag: "🇨🇫"),
            Country(countryName: "Burkina Faso", countryCode: "BF", countryCurrency: "XOF", countryFlag: "🇧🇫"),
            Country(countryName: "Eritrea", countryCode: "ER", countryCurrency: "ERN", countryFlag: "🇪🇷"),
            Country(countryName: "Tanzania", countryCode: "TZ", countryCurrency: "TZS", countryFlag: "🇹🇿"),
            Country(countryName: "South Korea", countryCode: "KR", countryCurrency: "KRW", countryFlag: "🇰🇷"),
            Country(countryName: "Jordan", countryCode: "JO", countryCurrency: "JOD", countryFlag: "🇯🇴"),
            Country(countryName: "Mauritania", countryCode: "MR", countryCurrency: "MRU", countryFlag: "🇲🇷"),
            Country(countryName: "Lithuania", countryCode: "LT", countryCurrency: "EUR", countryFlag: "🇱🇹"),
            Country(countryName: "United States Minor Outlying Islands", countryCode: "UM", countryCurrency: "USD", countryFlag: "🇺🇲"),
            Country(countryName: "Slovakia", countryCode: "SK", countryCurrency: "EUR", countryFlag: "🇸🇰"),
            Country(countryName: "Angola", countryCode: "AO", countryCurrency: "AOA", countryFlag: "🇦🇴"),
            Country(countryName: "Kazakhstan", countryCode: "KZ", countryCurrency: "KZT", countryFlag: "🇰🇿"),
            Country(countryName: "Moldova", countryCode: "MD", countryCurrency: "MDL", countryFlag: "🇲🇩"),
            Country(countryName: "Mali", countryCode: "ML", countryCurrency: "XOF", countryFlag: "🇲🇱"),
            Country(countryName: "Falkland Islands", countryCode: "FK", countryCurrency: "FKP", countryFlag: "🇫🇰"),
            Country(countryName: "Armenia", countryCode: "AM", countryCurrency: "AMD", countryFlag: "🇦🇲"),
            Country(countryName: "Samoa", countryCode: "WS", countryCurrency: "WST", countryFlag: "🇼🇸"),
            Country(countryName: "Jersey", countryCode: "JE", countryCurrency: "GBP", countryFlag: "🇯🇪"),
            Country(countryName: "Japan", countryCode: "JP", countryCurrency: "JPY", countryFlag: "🇯🇵"),
            Country(countryName: "Bolivia", countryCode: "BO", countryCurrency: "BOB", countryFlag: "🇧🇴"),
            Country(countryName: "Chile", countryCode: "CL", countryCurrency: "CLP", countryFlag: "🇨🇱"),
            Country(countryName: "United States", countryCode: "US", countryCurrency: "USD", countryFlag: "🇺🇸"),
            Country(countryName: "Saint Vincent and the Grenadines", countryCode: "VC", countryCurrency: "XCD", countryFlag: "🇻🇨"),
            Country(countryName: "Bermuda", countryCode: "BM", countryCurrency: "BMD", countryFlag: "🇧🇲"),
            Country(countryName: "Seychelles", countryCode: "SC", countryCurrency: "SCR", countryFlag: "🇸🇨"),
            Country(countryName: "British Indian Ocean Territory", countryCode: "IO", countryCurrency: "USD", countryFlag: "🇮🇴"),
            Country(countryName: "Guatemala", countryCode: "GT", countryCurrency: "GTQ", countryFlag: "🇬🇹"),
            Country(countryName: "Ecuador", countryCode: "EC", countryCurrency: "USD", countryFlag: "🇪🇨"),
            Country(countryName: "Martinique", countryCode: "MQ", countryCurrency: "EUR", countryFlag: "🇲🇶"),
            Country(countryName: "Tajikistan", countryCode: "TJ", countryCurrency: "TJS", countryFlag: "🇹🇯"),
            Country(countryName: "Malta", countryCode: "MT", countryCurrency: "EUR", countryFlag: "🇲🇹"),
            Country(countryName: "Gambia", countryCode: "GM", countryCurrency: "GMD", countryFlag: "🇬🇲"),
            Country(countryName: "Nigeria", countryCode: "NG", countryCurrency: "NGN", countryFlag: "🇳🇬"),
            Country(countryName: "Bahamas", countryCode: "BS", countryCurrency: "BSD", countryFlag: "🇧🇸"),
            Country(countryName: "Kosovo", countryCode: "XK", countryCurrency: "EUR", countryFlag: "🇽🇰"),
            Country(countryName: "Kuwait", countryCode: "KW", countryCurrency: "KWD", countryFlag: "🇰🇼"),
            Country(countryName: "Maldives", countryCode: "MV", countryCurrency: "MVR", countryFlag: "🇲🇻"),
            Country(countryName: "South Sudan", countryCode: "SS", countryCurrency: "SSP", countryFlag: "🇸🇸"),
            Country(countryName: "Iran", countryCode: "IR", countryCurrency: "IRR", countryFlag: "🇮🇷"),
            Country(countryName: "Albania", countryCode: "AL", countryCurrency: "ALL", countryFlag: "🇦🇱"),
            Country(countryName: "Brazil", countryCode: "BR", countryCurrency: "BRL", countryFlag: "🇧🇷"),
            Country(countryName: "Serbia", countryCode: "RS", countryCurrency: "RSD", countryFlag: "🇷🇸"),
            Country(countryName: "Belize", countryCode: "BZ", countryCurrency: "BZD", countryFlag: "🇧🇿"),
            Country(countryName: "Myanmar", countryCode: "MM", countryCurrency: "MMK", countryFlag: "🇲🇲"),
            Country(countryName: "Bhutan", countryCode: "BT", countryCurrency: "BTN", countryFlag: "🇧🇹"),
            Country(countryName: "Venezuela", countryCode: "VE", countryCurrency: "VES", countryFlag: "🇻🇪"),
            Country(countryName: "Liberia", countryCode: "LR", countryCurrency: "LRD", countryFlag: "🇱🇷"),
            Country(countryName: "Jamaica", countryCode: "JM", countryCurrency: "JMD", countryFlag: "🇯🇲"),
            Country(countryName: "Poland", countryCode: "PL", countryCurrency: "PLN", countryFlag: "🇵🇱"),
            Country(countryName: "Cayman Islands", countryCode: "KY", countryCurrency: "KYD", countryFlag: "🇰🇾"),
            Country(countryName: "Brunei", countryCode: "BN", countryCurrency: "BND", countryFlag: "🇧🇳"),
            Country(countryName: "Comoros", countryCode: "KM", countryCurrency: "KMF", countryFlag: "🇰🇲"),
            Country(countryName: "Guam", countryCode: "GU", countryCurrency: "USD", countryFlag: "🇬🇺"),
            Country(countryName: "Tonga", countryCode: "TO", countryCurrency: "TOP", countryFlag: "🇹🇴"),
            Country(countryName: "Kiribati", countryCode: "KI", countryCurrency: "AUD", countryFlag: "🇰🇮"),
            Country(countryName: "Ghana", countryCode: "GH", countryCurrency: "GHS", countryFlag: "🇬🇭"),
            Country(countryName: "Chad", countryCode: "TD", countryCurrency: "XAF", countryFlag: "🇹🇩"),
            Country(countryName: "Zimbabwe", countryCode: "ZW", countryCurrency: "ZWL", countryFlag: "🇿🇼"),
            Country(countryName: "Saint Martin", countryCode: "MF", countryCurrency: "EUR", countryFlag: "🇲🇫"),
            Country(countryName: "Mongolia", countryCode: "MN", countryCurrency: "MNT", countryFlag: "🇲🇳"),
            Country(countryName: "Portugal", countryCode: "PT", countryCurrency: "EUR", countryFlag: "🇵🇹"),
            Country(countryName: "American Samoa", countryCode: "AS", countryCurrency: "USD", countryFlag: "🇦🇸"),
            Country(countryName: "Republic of the Congo", countryCode: "CG", countryCurrency: "XAF", countryFlag: "🇨🇬"),
            Country(countryName: "Belgium", countryCode: "BE", countryCurrency: "EUR", countryFlag: "🇧🇪"),
            Country(countryName: "Israel", countryCode: "IL", countryCurrency: "ILS", countryFlag: "🇮🇱"),
            Country(countryName: "New Zealand", countryCode: "NZ", countryCurrency: "NZD", countryFlag: "🇳🇿"),
            Country(countryName: "Nicaragua", countryCode: "NI", countryCurrency: "NIO", countryFlag: "🇳🇮"),
            Country(countryName: "Anguilla", countryCode: "AI", countryCurrency: "XCD", countryFlag: "🇦🇮")
        ]
    }
    
    static func getCountryByName(name: String) -> Country? {
        countryData.first { $0.countryName.localizedUppercase == name.localizedUppercase }
    }
    
    static func getCountryByCode(code: String) -> Country? {
        countryData.first { $0.countryCode.localizedUppercase == code.localizedUppercase }
    }
    
    static func getCountryByCurrency(currency: String) -> Country? {
        countryData.first { $0.countryCurrency.localizedUppercase == currency.localizedUppercase }
    }
}

